.circleci/config.yml, .npmignore, android/src/main/java/io/textile/rnmobile/TextileNode.java, ios/TextileNode.m, lib/Textile/API/index.ts, lib/Textile/Models/index.ts, lib/Textile/__tests__/Api.ts, lib/Textile/index.ts, package.json
Should be cleaner now @andrewxhill . But defs needs a proper review.
=> Cherry-picks previous token updates to merge into master

lib/Textile/API/index.ts, lib/Textile/Models/index.ts, lib/Textile/Models/pb.ts, lib/Textile/Models/util.ts, lib/Textile/__tests__/API.ts, lib/Textile/index.ts, lib/index.ts, package.json, yarn.lock
rc42 includes new generated protobuf classes/interfaces. This PR implements their use where applicable.
So far I've simply updated existing TS code to use the new protobuf classes.
@sanderpick or anyone, are there any actual API updates that need to be made?
=> go-mobile upgrade

lib/Textile/Models/SDK.ts, lib/Textile/helpers.ts, lib/Textile/index.ts
=> Allows client to choose whatever background stopping function

ios/TextileNode.m, package.json
=> Swaps nil to @'' for most of the ios bridge methods

package.json, yarn.lock
=> Bump go-mobile

android/src/main/java/io/textile/rnmobile/TextileNode.java, ios/RNTextile.xcworkspace/contents.xcworkspacedata, ios/TextileNode.m, package.json, src/Textile/API/account.ts, src/Textile/API/cafes.ts, src/Textile/API/contacts.ts, src/Textile/API/feed.ts, src/Textile/API/files.ts, src/Textile/API/flags.ts, src/Textile/API/ignores.ts, src/Textile/API/index.ts, src/Textile/API/invites.ts, src/Textile/API/profile.ts, src/Textile/API/threads.ts, textile-react-native-sdk.podspec, yarn.lock
=> go-mobile@0.1.11

package.json, textile-react-native-sdk.podspec
=> New ios-textie to get a bug fix

android/build.gradle, android/src/main/java/io/textile/rnmobile/ProfileBridge.java, ios/ProfileBridge.m, package.json, src/profile.ts, textile-react-native-sdk.podspec
=> Updating native sdks, updating to accountThread

android/build.gradle, package.json, textile-react-native-sdk.podspec
=> Update native sdks

android/build.gradle, ios/TextileEvents.m, textile-react-native-sdk.podspec
=> Send error.localizedDescription

package.json, yarn.lock
Forgot to update js-types in the last PR.
=> Update js-types and package version

android/build.gradle, package.json, textile-react-native-sdk.podspec, yarn.lock
=> Update native sdks and js-types

android/build.gradle, android/src/main/java/io/textile/rnmobile/FilesBridge.java, ios/FilesBridge.m, package.json, src/files.ts, textile-react-native-sdk.podspec, yarn.lock
=> Update the native SDKs

textile-react-native-sdk.podspec
=> Update to latest ios-textile

android/build.gradle, package.json
Brings the android side to go-textile 0.2.6
=> Update android textile

package.json, src/cafes.ts
=> Fix refreshSession

package.json
=> New version number to avoid conflict with published versions

android/manifest.gradle, android/src/main/java/io/textile/rnmobile/FilesBridge.java, ios/FilesBridge.m, package.json, src/files.ts, textile-react-native-sdk.podspec
go-textile 0.5.2
base64 string as input to `addData`
=> Update to latest native sdks

android/manifest.gradle, package.json, textile-react-native-sdk.podspec
Signed-off-by: Sander Pick <sanderpick@gmail.com>
=> version: bump ios and android sdks

package.json
Signed-off-by: Sander Pick <sanderpick@gmail.com>
=> bump: v2.1.5

android/manifest.gradle, package.json, yarn.lock
=> Update to android-textile 1.1.6, js-types 0.5.4

android/manifest.gradle, android/src/main/java/io/textile/rnmobile/TextileBridge.java, ios/TextileBridge.m, package.json, src/textile.ts, textile-react-native-sdk.podspec
Updates to new initialize API that allows syncing an existing account
=> Native sdks 2.0

android/manifest.gradle, package.json, textile-react-native-sdk.podspec, yarn.lock
=> updating all the files to native sdks 2.0.1 and go-textile 0.6.2

android/manifest.gradle, package.json, textile-react-native-sdk.podspec
=> Update to native sdks 2.0.2, core 0.6.4

android/manifest.gradle, package.json, textile-react-native-sdk.podspec
=> Updating native sdks

android/manifest.gradle, android/src/main/java/io/textile/rnmobile/CafesBridge.java, ios/CafesBridge.m, package.json, textile-react-native-sdk.podspec, yarn.lock
Includes a signature change on `checkMessages`, which now takes a callback.
=> Update SDKs to 0.7.0

android/manifest.gradle, package.json
Signed-off-by: andrew <andrew@textile.io>
=> Pulling in comment crash fix

ios/TextileBridge.m, package.json, textile-react-native-sdk.podspec
=> Update to ios-textile 2.0.10

package.json, src/ipfs.ts
prob should tag a release of the sdk with this
=> fixes buffer import for dataAtPath

android/src/main/java/io/textile/rnmobile/CafesBridge.java, ios/CafesBridge.m, src/cafes.ts
=> Update some cafe api param names

package.json, yarn.lock
=> Prep release

ios/IpfsBridge.m, ios/TextileEvents.m, package.json, textile-react-native-sdk.podspec
=> Fix a few compilation errors, new Textile ios dependency

android/src/main/java/io/textile/rnmobile/TextileBridge.java, package.json
=> use Integer instead of long
